"""Write hand-curated city summaries used on the hidden city selection screen."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "city_curated_summaries.json"


CURATED = {
    "Bodrum": ("Marina geceleri ve beyaz evler", "Parlak marinalar, beach club ritmi ve beyaz sokaklar etrafında hareketli, konforlu bir kıyı tatili hissi verir.", ["deniz", "gece", "konfor"]),
    "Marmaris": ("Koylar ve tekne rotaları", "Çam tepeleri arasındaki uzun koylar, tekne turları ve akşamüstü sahil yürüyüşleriyle canlı ama doğaya yakın bir deniz molası sunar.", ["deniz", "tekne", "canlı"]),
    "Fethiye": ("Lagünler ve havadan manzara", "Turkuaz lagünler, yamaç paraşütü manzarası ve doğa parkurlarıyla hem deniz hem macera isteyenlere açılır.", ["deniz", "macera", "doğa"]),
    "Cesme": ("Rüzgar, plaj ve şık sahil", "Rüzgarlı plajlar, sörf enerjisi ve şık yaz akşamlarıyla sosyal, rahat ve biraz lüks bir kıyı atmosferi kurar.", ["deniz", "sörf", "sosyal"]),
    "Datca": ("Sessiz koylar ve yavaş tempo", "Kalabalıktan uzak koylar, badem ağaçları ve sakin akşam sofralarıyla yavaş, sade ve huzurlu bir kaçış hissi verir.", ["sakin", "deniz", "yavaş"]),
    "Antalya": ("Eski kent ve geniş sahil", "Tarihi sokaklar, büyük sahiller ve kolay ulaşım birleşir; hem kültür hem deniz isteyenler için dengeli bir rota olur.", ["tarih", "deniz", "kolay"]),
    "Alanya": ("Kale manzarası ve sıcak sahil", "Uzun plajlar, tepeden bakan kale silueti ve sıcak yaz temposuyla pratik, güneşli bir deniz tatili verir.", ["deniz", "güneş", "kale"]),
    "Kas": ("Dalış ve küçük liman", "Küçük liman atmosferi, dalış noktaları ve kayalık koylarıyla daha butik, sportif ve berrak bir kıyı deneyimi sunar.", ["dalış", "butik", "deniz"]),
    "Side": ("Antik taşlar ve sahil", "Denize yakın antik kalıntılar, yürünebilir sahil hattı ve sakin akşamlar sayesinde tarih ile plajı aynı yerde toplar.", ["tarih", "sahil", "yürüyüş"]),
    "Kemer": ("Dağ eteklerinde deniz", "Toros etekleri, çakıllı koylar ve resort rahatlığıyla doğa manzaralı, kolay planlanan bir Akdeniz molası verir.", ["deniz", "dağ", "resort"]),
    "Trabzon": ("Yamaç şehir ve yayla kapısı", "Karadeniz yamaçları, manastır rotaları ve yaylalara açılan yollarla yağmurlu, yeşil ve karakterli bir keşif sunar.", ["doğa", "tarih", "yayla"]),
    "Uzungol": ("Göl çevresinde sisli mola", "Dağların arasındaki göl, sisli sabahlar ve ahşap konaklama hissiyle fotoğraf odaklı sakin bir doğa molasıdır.", ["göl", "sakin", "fotoğraf"]),
    "Ayder": ("Yayla, kaplıca ve yürüyüş", "Yayla evleri, kaplıca fikri ve yüksek patikalarla serin havalı, dinlendirici bir doğa kaçışı sunar.", ["yayla", "kaplıca", "doğa"]),
    "Artvin": ("Vadiler ve yüksek geçitler", "Derin vadiler, dağ yolları ve bakir manzaralarla kalabalıktan uzak, güçlü bir açık hava rotası verir.", ["vadi", "macera", "doğa"]),
    "Rize": ("Çay tepeleri ve yağmur", "Çay bahçeleri, bulutlu tepeler ve şelale yollarıyla yeşilin ağır bastığı, yavaş ve nemli bir Karadeniz hissi kurar.", ["çay", "yeşil", "sakin"]),
    "Kapadokya": ("Peri bacaları ve balon sabahı", "Taş vadiler, gün doğumu balonları ve mağara konaklama hissiyle çok görsel, romantik ve farklı bir rota sunar.", ["balon", "tarih", "fotoğraf"]),
    "Efes": ("Antik kent odağı", "Sütunlu caddeler, tiyatro kalıntıları ve arkeoloji yoğunluğu ile tarihi doğrudan yürüyerek hissettiren bir duraktır.", ["antik", "tarih", "arkeoloji"]),
    "Pamukkale": ("Beyaz teraslar ve antik havuz", "Beyaz travertenler, sıcak su fikri ve antik kent kalıntılarıyla görsel açıdan çok ayırt edici bir mola verir.", ["traverten", "tarih", "fotoğraf"]),
    "Mardin": ("Taş konaklar ve Mezopotamya manzarası", "Sarı taş sokaklar, teraslardan ova manzarası ve çok katmanlı kültür dokusuyla ağır tempolu, atmosferik bir keşiftir.", ["taş", "kültür", "tarih"]),
    "Sanliurfa": ("İnanç, pazar ve eski hikayeler", "Balıklıgöl çevresi, çarşı kokuları ve kadim anlatılarla manevi, yerel ve tarih hissi kuvvetli bir rota olur.", ["inanç", "çarşı", "tarih"]),
    "Istanbul": ("Boğaz, semtler ve büyük kültür", "Vapur sesleri, tarihi yarımada, müzeler ve yoğun semt hayatıyla yüksek enerjili, katmanlı bir şehir deneyimi sunar.", ["şehir", "tarih", "yemek"]),
    "Izmir": ("Rahat kordon ve Ege şehri", "Deniz kenarı yürüyüşleri, rahat kent temposu ve yakın çevre kaçamaklarıyla hafif, pratik ve sosyal bir mola verir.", ["şehir", "rahat", "deniz"]),
    "Gaziantep": ("Mutfak ve müze odağı", "Baklava, kebap, çarşı ve güçlü müze içeriğiyle yemek merkezli ama kültür tarafı da dolu bir şehir kaçamağıdır.", ["yemek", "müze", "çarşı"]),
    "Bursa": ("Osmanlı dokusu ve yeşil yamaçlar", "Tarihi külliyeler, çarşılar ve dağ etekleriyle kültür, yemek ve doğa molasını dengeli tutar.", ["tarih", "yemek", "dağ"]),
    "Ankara": ("Müze, anıt ve sakin başkent", "Anıtsal yapılar, müzeler ve daha düzenli şehir temposuyla kalabalık turizmden uzak bir kültür günü sunar.", ["müze", "başkent", "sakin"]),
    "Kotor": ("Fiyort gibi koy ve taş surlar", "Dağların kapattığı koy, sur içi sokaklar ve kısa tırmanış manzaralarıyla kompakt ama etkileyici bir Adriyatik durağıdır.", ["koy", "sur", "manzara"]),
    "Mostar": ("Köprü ve nehir kenarı", "Taş köprü çevresi, nehir sesi ve küçük çarşı dokusuyla kısa ama duygusu güçlü bir Balkan molası verir.", ["köprü", "nehir", "tarih"]),
    "Tiran": ("Renkli meydanlar ve genç tempo", "Geniş meydanlar, kafeler ve yakın dağ kaçamaklarıyla uygun bütçeli, rahat ve genç bir şehir hissi taşır.", ["şehir", "bütçe", "kafe"]),
    "Beograd": ("Nehir kıyısı ve gece hayatı", "Tuna-Sava buluşması, kaleler ve canlı gece kültürüyle sosyal, enerjik ve bütçe dostu bir şehir deneyimidir.", ["gece", "nehir", "şehir"]),
    "Uskup": ("Heykeller, çarşı ve Balkan karışımı", "Taş köprü, eski çarşı ve farklı dönemlerin mimarisiyle kısa sürede çok kontrast gösteren bir şehir molasıdır.", ["çarşı", "köprü", "şehir"]),
    "Baku": ("Hazar kıyısı ve modern siluet", "Alev kuleleri, sahil bulvarı ve eski şehir dokusuyla modern parıltı ile tarih karışımı bir rota verir.", ["modern", "sahil", "tarih"]),
    "Tiflis": ("Yamaç sokaklar ve sıcak avlular", "Renkli balkonlar, hamam bölgesi ve şarap sofralarıyla sıcak, yürünebilir ve karakterli bir şehir hissi kurar.", ["sokak", "yemek", "tarih"]),
    "Semerkant": ("Mavi kubbeler ve İpek Yolu", "Büyük meydanlar, mavi çiniler ve anıtsal medreselerle görkemli, tarih yoğun bir İpek Yolu deneyimi sunar.", ["kubbe", "tarih", "mimari"]),
    "Buhara": ("Avlu medreseleri ve eski pazar", "Daha yavaş sokaklar, avlulu yapılar ve eski ticaret hissiyle zamana yayılmış bir kültür rotasıdır.", ["pazar", "medrese", "yavaş"]),
    "Taskent": ("Geniş bulvar ve Sovyet-modern karışımı", "Metro durakları, geniş caddeler ve pazar hayatıyla düzenli, pratik ve şehir odaklı bir Orta Asya durağıdır.", ["metro", "pazar", "şehir"]),
    "Marakes": ("Baharat, avlu ve kızıl sokaklar", "Medina kalabalığı, riad avluları ve baharat kokularıyla yoğun, renkli ve duyusal bir şehir deneyimi verir.", ["medina", "renk", "pazar"]),
    "Fes": ("Labirent medina ve zanaat", "Dar sokaklar, tabakhane manzaraları ve geleneksel üretim dokusuyla daha eski, yoğun ve kültür odaklı bir keşiftir.", ["zanaat", "medina", "tarih"]),
    "Tunus": ("Akdeniz şehir dokusu ve pazar", "Medina, sahil esintisi ve yakın antik kalıntılarla şehir, tarih ve denizi kısa mesafede birleştirir.", ["medina", "sahil", "tarih"]),
    "Sidi Bou Said": ("Mavi beyaz sokak ve deniz manzarası", "Beyaz duvarlar, mavi kapılar ve denize bakan kafelerle hafif, fotojenik ve sakin bir Akdeniz molasıdır.", ["mavi", "kafe", "deniz"]),
    "Kairouan": ("Sessiz kutsal şehir dokusu", "Sade sokaklar, cami çevresi ve geleneksel halı/pazar hissiyle daha içe dönük bir kültür durağı sunar.", ["inanç", "sakin", "tarih"]),
    "Tokyo": ("Neon, düzen ve sonsuz seçenek", "Metro ağları, küçük lokantalar ve neonlu mahallelerle yüksek tempolu, düzenli ve keşfi bitmeyen bir şehir deneyimidir.", ["neon", "yemek", "şehir"]),
    "Kyoto": ("Tapınaklar ve mevsimlik bahçeler", "Ahşap sokaklar, tapınak bahçeleri ve çay ritüeli hissiyle yavaş, zarif ve kültür ağırlıklı bir rota sunar.", ["tapınak", "bahçe", "kültür"]),
    "Osaka": ("Sokak yemeği ve nehir ışıkları", "Kanal çevresi, parlak tabelalar ve güçlü sokak yemeği kültürüyle daha rahat, lezzet odaklı bir Japonya molasıdır.", ["yemek", "gece", "şehir"]),
    "Seoul": ("K-pop enerjisi ve saraylar", "Saray avluları, alışveriş caddeleri ve hızlı gece temposuyla gelenek ile pop kültürü yan yana taşır.", ["pop", "saray", "şehir"]),
    "Busan": ("Plaj, balık pazarı ve tepeli mahalleler", "Deniz kenarı, balık pazarı ve renkli yamaç mahalleleriyle daha kıyı odaklı, rahat bir Kore rotasıdır.", ["plaj", "pazar", "tepe"]),
    "Singapur": ("Tropik düzen ve modern şehir", "Bahçeler, temiz ulaşım ve çok kültürlü yemek alanlarıyla kompakt, güvenli ve modern bir şehir deneyimi verir.", ["modern", "yemek", "bahçe"]),
    "Hong Kong": ("Liman silueti ve dikey şehir", "Feribotlar, gökdelenler, tepe manzarası ve yoğun sokak yemekleriyle sıkışık ama çok güçlü bir metropol hissi sunar.", ["liman", "gökdelen", "yemek"]),
    "Kuala Lumpur": ("Kuleler ve sokak lezzetleri", "Modern kuleler, alışveriş bölgeleri ve gece pazarlarıyla uygun bütçeli, yemek odaklı bir büyük şehir molasıdır.", ["kule", "pazar", "yemek"]),
    "Penang": ("Duvar sanatı ve sokak mutfağı", "Renkli eski sokaklar, mural rotaları ve baharatlı yemeklerle yavaş yürüyerek keşfedilen bir ada şehridir.", ["mural", "yemek", "ada"]),
    "Macau": ("Portekiz izleri ve ışıltı", "Taş meydanlar, yumurtalı tatlılar ve casino ışıklarıyla Avrupa mirası ile gösterişli geceyi karıştırır.", ["ışık", "miras", "tatlı"]),
    "Rio de Janeiro": ("Plaj, tepe ve samba", "İkonik tepeler, geniş plajlar ve müzikli sokak enerjisiyle dışa dönük, güneşli ve ritimli bir rota sunar.", ["plaj", "müzik", "manzara"]),
    "Buenos Aires": ("Tango ve geniş bulvarlar", "Kafeler, kitapçılar, tango salonları ve Avrupa etkili mahallelerle kültürlü, akşam odaklı bir şehir hissi verir.", ["tango", "kafe", "şehir"]),
    "Lima": ("Pasifik kıyısı ve gastronomi", "Okyanus kıyısı, modern mahalleler ve güçlü restoran sahnesiyle yemek merkezli sofistike bir mola sunar.", ["yemek", "okyanus", "şehir"]),
    "Bogota": ("Yüksek rakım ve sanat mahalleleri", "Dağ eteğinde müzeler, grafitili sokaklar ve kahve kültürüyle serin, yaratıcı bir şehir deneyimidir.", ["müze", "kahve", "sanat"]),
    "Santiago": ("And dağları önünde düzenli şehir", "Geniş caddeler, şehir parkları ve arka plandaki dağ siluetiyle pratik, sakin ve modern bir mola verir.", ["dağ", "şehir", "park"]),
    "Patagonia": ("Buzul, rüzgar ve uzak yürüyüş", "Sert rüzgar, büyük buzul manzaraları ve uzun yürüyüş rotalarıyla doğa gücü yüksek, zahmetli bir maceradır.", ["buzul", "trekking", "uzak"]),
    "Machu Picchu": ("Dağ üstünde antik rota", "Sisli dağ geçitleri, taş teraslar ve tarihi yürüyüş hissiyle ikonik, fiziksel olarak ödüllendirici bir deneyim sunar.", ["antik", "dağ", "yürüyüş"]),
    "Amazon": ("Nehir, orman ve vahşi yaşam", "Yoğun nem, tekne yolculukları ve orman sesleriyle konfor yerine keşif ve doğa merakı isteyenlere uygundur.", ["orman", "nehir", "vahşi"]),
    "Galapagos": ("Ada faunası ve berrak su", "Eşsiz hayvan gözlemleri, volkanik kıyılar ve şnorkel rotalarıyla doğa belgeseli gibi bir ada deneyimi verir.", ["ada", "hayvan", "şnorkel"]),
    "Uyuni": ("Tuz düzlüğü ve sonsuz ufuk", "Aynalı tuz zemini, yüksek rakım ve gerçeküstü fotoğraf sahneleriyle minimalist ama unutulmaz bir rota sunar.", ["tuz", "fotoğraf", "ufuk"]),
    "Bali": ("Tapınak, pirinç terası ve deniz", "Pirinç tarlaları, tapınak törenleri, surf kıyıları ve wellness kültürüyle yumuşak tempolu tropik bir karışım verir.", ["tropik", "wellness", "tapınak"]),
    "Bangkok": ("Tapınaklar ve sokak lezzeti", "Altın tapınaklar, nehir tekneleri, gece pazarları ve kaotik trafikle yoğun, lezzetli ve enerjik bir şehir sunar.", ["tapınak", "pazar", "yemek"]),
    "Phuket": ("Plaj kulüpleri ve ada turları", "Geniş plajlar, tekneyle ada gezileri ve canlı gece bölgeleriyle sosyal, güneşli ve kolay planlanan bir tatildir.", ["plaj", "tekne", "gece"]),
    "Siem Reap": ("Tapınak şafakları", "Dev tapınak kompleksleri, gün doğumu manzaraları ve yavaş kasaba akşamlarıyla tarih ve fotoğraf odaklıdır.", ["tapınak", "tarih", "fotoğraf"]),
    "Krabi": ("Kireçtaşı kayalıkları ve koylar", "Dramatik kayalıklar, longtail tekneler ve sakin koylarla daha doğal, manzaralı ve deniz odaklı bir rota verir.", ["kayalık", "tekne", "deniz"]),
    "Ho Chi Minh": ("Motosiklet temposu ve tarih", "Hızlı sokak akışı, savaş tarihi durakları ve güçlü sokak yemeğiyle canlı, yoğun ve şehir odaklıdır.", ["motosiklet", "tarih", "yemek"]),
    "Hanoi": ("Göl, eski mahalle ve kahve", "Dar eski sokaklar, göl çevresi ve kahve kültürüyle daha nostaljik, yürüyüşlü ve yemek odaklı bir şehir sunar.", ["kahve", "eski şehir", "yemek"]),
    "Goa": ("Plaj, koloni izleri ve rahat gece", "Palmiye plajları, Portekiz etkili sokaklar ve gevşek gece temposuyla rahat, sosyal bir kıyı kaçamağıdır.", ["plaj", "rahat", "gece"]),
    "Jaipur": ("Pembe şehir ve saraylar", "Saray avluları, kaleler ve renkli pazarlarla görkemli, fotojenik ve alışveriş hissi güçlü bir kültür rotasıdır.", ["saray", "pazar", "renk"]),
    "Varanasi": ("Nehir ritüelleri ve manevi yoğunluk", "Ghat merdivenleri, sabah tekneleri ve tören atmosferiyle duygusu ağır, çok katmanlı bir deneyim verir.", ["nehir", "ritüel", "manevi"]),
    "Punta Cana": ("Resort plaj ve kolay dinlenme", "Beyaz kumsal, her şey dahil konfor ve düşük plan yüküyle tamamen dinlenmeye dönük tropik bir seçenek sunar.", ["resort", "plaj", "dinlenme"]),
    "Havana": ("Renkli sokaklar ve eski arabalar", "Kolonyal cepheler, müzikli meydanlar ve nostaljik araçlarla ritimli, sıcak ve fotojenik bir şehir molasıdır.", ["müzik", "renk", "tarih"]),
    "Barbados": ("Sakin ada ve turkuaz kıyı", "Yumuşak plajlar, rom kültürü ve ada temposuyla daha rahat, güneşli ve deniz odaklı bir kaçış verir.", ["ada", "plaj", "rahat"]),
    "Nassau": ("Kısa ada kaçamağı ve parlak deniz", "Kristal su, liman çevresi ve kolay ada aktiviteleriyle pratik, renkli ve kısa tatil hissi taşır.", ["ada", "deniz", "liman"]),
    "Montego Bay": ("Reggae ritmi ve sahil resortu", "Plaj resortları, müzik enerjisi ve tropik akşamlarla sosyal, rahat ve güneşli bir ada deneyimidir.", ["reggae", "resort", "plaj"]),
    "Zanzibar": ("Baharat adası ve taş şehir", "Beyaz kumsallar, baharat kokuları ve taş sokaklar arasında deniz ile kültürü birlikte sunar.", ["baharat", "ada", "deniz"]),
    "Serengeti": ("Safari ufku ve büyük göç hissi", "Geniş savanlar, vahşi yaşam takibi ve gün doğumu araç rotalarıyla doğa gözlemi merkezli bir maceradır.", ["safari", "vahşi", "savan"]),
    "Nairobi": ("Şehir ve safari eşiği", "Modern şehir temposu, kahve molaları ve yakın doğal yaşam alanlarıyla Afrika keşfine pratik bir başlangıç verir.", ["şehir", "safari", "kahve"]),
    "Kilimanjaro": ("Zirve hedefi ve fiziksel meydan okuma", "Yüksek irtifa yürüyüşü, kamp düzeni ve zirve motivasyonuyla rahat tatilden çok hedef odaklı bir maceradır.", ["zirve", "trekking", "kamp"]),
    "Kigali": ("Düzenli tepeler ve sakin şehir", "Temiz caddeler, yeşil tepeler ve ağır tarih belleğiyle sakin, düzenli ve düşünceli bir şehir molasıdır.", ["tepe", "sakin", "tarih"]),
    "Petra": ("Kayaya oyulmuş antik geçit", "Dar kanyon yürüyüşü, kırmızı kaya cepheleri ve antik kent hissiyle güçlü, sinematik bir tarih rotasıdır.", ["kanyon", "antik", "kaya"]),
    "Wadi Rum": ("Çöl kampı ve yıldızlı gece", "Kızıl kumlar, kaya kemerleri, jeep rotaları ve yıldızlı kamp geceleriyle açık alan macerası verir.", ["çöl", "kamp", "yıldız"]),
    "Olu Deniz": ("Lagün ve yamaç paraşütü", "Durgun mavi lagün, yüksekten süzülme fikri ve yazlık sahil düzeniyle deniz-macera dengesini kurar.", ["lagün", "paraşüt", "deniz"]),
    "Kahire": ("Nil, müze ve piramit gölgesi", "Büyük şehir kaosu, antik eser yoğunluğu ve Nil çevresiyle yorucu ama tarih açısından çok güçlü bir deneyimdir.", ["piramit", "müze", "şehir"]),
    "Luxor": ("Tapınak vadisi ve Nil kıyısı", "Antik tapınaklar, mezar vadileri ve nehir kıyısı gün batımlarıyla açık hava müzesi gibi ilerler.", ["tapınak", "nil", "antik"]),
    "Maldivler": ("Su üstü sakinlik ve mercan", "Turkuaz lagünler, mercan şnorkeli ve izole konaklama düzeniyle romantik, pahalı ve tamamen dinlenmelik bir kaçıştır.", ["lagün", "lüks", "şnorkel"]),
    "Colombo": ("Okyanus kıyısı ve ada başlangıcı", "Sahil yürüyüşleri, pazarlar ve kolonyal izlerle Sri Lanka rotasına şehirli, sıcak bir giriş verir.", ["okyanus", "pazar", "şehir"]),
    "Kathmandu": ("Tapınak meydanları ve dağ hazırlığı", "Stupalar, kalabalık meydanlar ve trekking öncesi hazırlık atmosferiyle manevi ve dağlara yakın bir şehir sunar.", ["tapınak", "dağ", "şehir"]),
    "Pokhara": ("Göl kenarı ve Himalaya manzarası", "Sakin göl kıyısı, dağ silueti ve yamaç paraşütü seçeneğiyle dinlenme ile macerayı yumuşak birleştirir.", ["göl", "dağ", "macera"]),
    "Galle": ("Surlu liman ve tropik sokaklar", "Kolonyal surlar, okyanus esintisi ve butik kafelerle yavaş yürüyüşlü, zarif bir ada şehri verir.", ["sur", "okyanus", "butik"]),
    "Roma": ("Antik katman ve meydan hayatı", "Forum kalıntıları, çeşmeli meydanlar ve uzun yemek molalarıyla tarih ile gündelik hayatı iç içe sunar.", ["antik", "meydan", "yemek"]),
    "Floransa": ("Rönesans sanatı ve taş sokak", "Müzeler, kubbe manzarası ve atölye hissiyle sanat ağırlıklı, yürünebilir ve zarif bir şehir deneyimidir.", ["sanat", "müze", "kubbe"]),
    "Barselona": ("Mimari, plaj ve gece", "Gaudi yapıları, mahalle pazarları ve deniz yakınlığıyla kültür, yemek ve sosyal hayatı aynı potada toplar.", ["mimari", "plaj", "gece"]),
    "Atina": ("Akropol ve mahalle tavernaları", "Antik tepe manzarası, sıcak mahalleler ve Ege mutfağıyla tarih odaklı ama rahat bir şehir molasıdır.", ["antik", "yemek", "şehir"]),
    "Santorini": ("Beyaz teraslar ve kaldera", "Uçurum köyleri, gün batımı kalabalığı ve butik konaklama hissiyle romantik, görsel ve pahalı bir ada kaçışıdır.", ["ada", "günbatımı", "romantik"]),
    "Paris": ("Müze, bulvar ve zarif yürüyüş", "Büyük müzeler, nehir kıyısı yürüyüşleri ve kafe molalarıyla klasik, estetik ve kültür yoğun bir şehir sunar.", ["müze", "kafe", "nehir"]),
    "Amsterdam": ("Kanallar ve bisikletli şehir", "Kanal evleri, müzeler ve bisiklet temposuyla kompakt, rahat ve yürüyerek keşfedilen bir Avrupa molasıdır.", ["kanal", "bisiklet", "müze"]),
    "Londra": ("Müzeler ve çok merkezli metropol", "Ücretsiz müzeler, pazar mahalleleri ve tiyatro akşamlarıyla geniş, çeşitli ve planlı gezmeyi sevenlere uygundur.", ["müze", "pazar", "metropol"]),
    "Bruksel": ("Meydan, çikolata ve kısa şehir molası", "Görkemli meydan, çizgi roman dokusu ve çikolata molalarıyla kısa, kolay ve lezzetli bir Avrupa durağıdır.", ["meydan", "çikolata", "şehir"]),
    "Dublin": ("Pub kültürü ve edebi sokaklar", "Canlı pub akşamları, taş sokaklar ve hikaye anlatan müzelerle samimi, müzikli bir şehir hissi verir.", ["pub", "müzik", "edebiyat"]),
    "Oslo": ("Fiyort kıyısı ve sade tasarım", "Deniz kıyısı mimarisi, müzeler ve yakın doğa rotalarıyla sakin, düzenli ve pahalı bir kuzey molasıdır.", ["fiyort", "tasarım", "sakin"]),
    "Stockholm": ("Adalar ve kuzey zarafeti", "Su yolları, tarihi ada sokakları ve tasarım mağazalarıyla ferah, estetik ve ölçülü bir şehir deneyimidir.", ["ada", "tasarım", "su"]),
    "Kopenhag": ("Bisiklet, liman ve rahat yaşam", "Renkli liman, bisiklet düzeni ve yeni nordik yemek kültürüyle konforlu, sade ve keyifli bir şehir sunar.", ["bisiklet", "liman", "yemek"]),
    "Helsinki": ("Sakin liman ve sauna kültürü", "Deniz kıyısı, tasarım mağazaları ve sauna ritüeliyle sessiz, temiz ve kısa kaçamak hissi verir.", ["sauna", "tasarım", "liman"]),
    "Tromso": ("Kutup gecesi ve kuzey ışığı", "Karlı manzaralar, kuzey ışığı avı ve soğuk deniz kıyısı atmosferiyle özel mevsim isteyen bir rota olur.", ["kuzey ışığı", "kar", "soğuk"]),
    "Dubai": ("Gökdelen, çöl ve lüks düzen", "Yüksek kuleler, alışveriş merkezleri, çöl aktiviteleri ve kusursuz servis hissiyle gösterişli ve konfor odaklıdır.", ["lüks", "çöl", "modern"]),
    "Abu Dabi": ("Müze, cami ve sakin lüks", "Büyük cami, kültür adası ve daha düzenli sahil yaşamıyla gösterişten çok sakin konfor hissi verir.", ["cami", "müze", "lüks"]),
    "Doha": ("Körfez silueti ve müze rotası", "Modern sahil, İslam sanatı müzeleri ve çöl yakınlığıyla kompakt, sıcak ve kültürlü bir körfez molasıdır.", ["müze", "sahil", "çöl"]),
    "Muskat": ("Dağ, deniz ve beyaz şehir", "Beyaz binalar, sert dağ fonu ve sakin kıyılarla daha doğal, ağırbaşlı ve kalabalıktan uzak bir Körfez rotasıdır.", ["dağ", "deniz", "sakin"]),
    "Riyad": ("Çöl başkenti ve yeni şehir", "Geniş bulvarlar, yeni kültür alanları ve çöl kenarı gezileriyle modernleşen, farklı bir başkent deneyimi verir.", ["başkent", "çöl", "modern"]),
    "New York": ("Gökdelen ve mahalle enerjisi", "Müzeler, parklar, farklı mahalleler ve gece ışıklarıyla hızlı, yoğun ve seçenekleri bitmeyen bir metropol sunar.", ["metropol", "müze", "gece"]),
    "Los Angeles": ("Sahil, stüdyo ve geniş mesafe", "Plajlar, sinema kültürü ve araba gerektiren dağınık mahallelerle güneşli ama plan isteyen bir şehir deneyimidir.", ["sinema", "sahil", "araba"]),
    "Miami": ("Art deco, Latin ritmi ve plaj", "Renkli sahil mimarisi, Latin müziği ve gece hayatıyla sıcak, sosyal ve deniz odaklı bir şehir kaçamağıdır.", ["plaj", "latin", "gece"]),
    "Toronto": ("Çok kültürlü mahalleler ve göl kıyısı", "Göl kenarı, dünya mutfakları ve düzenli büyük şehir hissiyle kolay, güvenli ve yemek odaklı bir mola verir.", ["göl", "yemek", "şehir"]),
    "San Francisco": ("Tepeler, köprü ve yaratıcı mahalleler", "Dik sokaklar, körfez manzarası ve teknoloji-kültür karışımı mahallelerle serin, karakterli bir şehir sunar.", ["köprü", "tepe", "şehir"]),
    "Cancun": ("Resort şeridi ve Karayip denizi", "Turkuaz su, resort düzeni ve yakın Maya rotalarıyla kolay, güneşli ve konforlu bir tatil seçeneğidir.", ["resort", "deniz", "maya"]),
    "Meksiko": ("Müze, pazar ve dev şehir", "Büyük müzeler, sokak yemeği, tarihi meydanlar ve yaratıcı mahallelerle yoğun ama çok zengin bir metropoldür.", ["müze", "yemek", "metropol"]),
    "San Jose": ("Doğa rotalarına şehir kapısı", "Kahve kültürü, müzeler ve yağmur ormanı/volkan gezilerine yakınlığıyla pratik bir başlangıç noktasıdır.", ["kahve", "volkan", "şehir"]),
    "Panama City": ("Kanal, gökdelen ve eski mahalle", "Modern siluet, tarihi yarımada ve kanal mühendisliğiyle kısa sürede farklı yüzler gösteren tropik bir şehir olur.", ["kanal", "modern", "tarih"]),
    "Cartagena": ("Renkli sur içi ve Karayip akşamı", "Kolonyal balkonlar, sıcak meydanlar ve deniz esintisiyle romantik, renkli ve yürüyüş odaklı bir şehir sunar.", ["renk", "sur", "karayip"]),
    "Sydney": ("Liman, opera ve şehir plajı", "İkonik liman, feribotlar ve surf plajlarıyla açık havada yaşayan, enerjik ve rahat bir metropol hissi verir.", ["liman", "plaj", "şehir"]),
    "Melbourne": ("Kafe sokakları ve sanat havası", "Gizli pasajlar, kahve kültürü, galeri ve spor etkinlikleriyle daha kültürlü, serin ve mahalle odaklıdır.", ["kafe", "sanat", "mahalle"]),
    "Queenstown": ("Göl kıyısında adrenalin", "Dağ gölü, bungee/jetboat seçenekleri ve yürüyüş rotalarıyla küçük ama macera yoğun bir doğa üssüdür.", ["macera", "göl", "dağ"]),
    "Suva": ("Pasifik başkenti ve yerel pazar", "Tropik yağmur, pazar hayatı ve yerel gündelik ritimle resorttan çok gerçek ada yaşamı hissi verir.", ["pazar", "ada", "yerel"]),
    "Papeete": ("Lagün kapısı ve Polinezya pazarı", "Renkli pazarlar, liman çevresi ve uzak ada hissiyle pahalı ama çok özel bir Pasifik başlangıcıdır.", ["lagün", "pazar", "pasifik"]),
}


def main() -> None:
    old_path = ROOT / "data" / "hidden_summaries.json"
    old = json.loads(old_path.read_text(encoding="utf-8")) if old_path.exists() else {}
    out = {}
    for city, (title, summary, tags) in CURATED.items():
        old_item = old.get(city, {})
        out[city] = {
            "hidden_title": title,
            "hidden_summary": summary,
            "hidden_tags": tags,
            "reveal_summary": f"{city}: {summary}",
            "text_source": old_item.get("text_source", ""),
        }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(out)} curated summaries to {OUT}")


if __name__ == "__main__":
    main()
